/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as InsightsInsightIdRouteImport } from './routes/insights.$insightId'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => TopicsRoute,
} as any)
const InsightsInsightIdRoute = InsightsInsightIdRouteImport.update({
  id: '/$insightId',
  path: '/$insightId',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impact'
    | '/insights'
    | '/reviews'
    | '/settings'
    | '/topics'
    | '/insights/$insightId'
    | '/topics/$topicId'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impact'
    | '/reviews'
    | '/settings'
    | '/topics'
    | '/insights/$insightId'
    | '/topics/$topicId'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/impact'
    | '/insights'
    | '/reviews'
    | '/settings'
    | '/topics'
    | '/insights/$insightId'
    | '/topics/$topicId'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpactRoute: typeof ImpactRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  TopicsRoute: typeof TopicsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/insights/$insightId': {
      id: '/insights/$insightId'
      path: '/$insightId'
      fullPath: '/insights/$insightId'
      preLoaderRoute: typeof InsightsInsightIdRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsInsightIdRoute: typeof InsightsInsightIdRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsInsightIdRoute: InsightsInsightIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface TopicsRouteChildren {
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsTopicIdRoute: TopicsTopicIdRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpactRoute: ImpactRoute,
  InsightsRoute: InsightsRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  TopicsRoute: TopicsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
